// Stable event codes for audit logging
// These codes should remain consistent for search and alerting

// Auth & Security Events
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET';
export const AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED';
export const AUTH_MFA_ENROLLED = 'AUTH_MFA_ENROLLED';
export const AUTH_MFA_REMOVED = 'AUTH_MFA_REMOVED';
export const AUTH_IMPERSONATION_STARTED = 'AUTH_IMPERSONATION_STARTED';
export const AUTH_IMPERSONATION_ENDED = 'AUTH_IMPERSONATION_ENDED';
export const AUTH_SESSION_TERMINATED = 'AUTH_SESSION_TERMINATED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// User Events
export const USER_CREATED = 'USER_CREATED';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_SUSPENDED = 'USER_SUSPENDED';
export const USER_REINSTATED = 'USER_REINSTATED';
export const USER_ROLE_GRANTED = 'USER_ROLE_GRANTED';
export const USER_ROLE_REVOKED = 'USER_ROLE_REVOKED';
export const USER_MERGED = 'USER_MERGED';
export const USER_VACATION_ENABLED = 'USER_VACATION_ENABLED';
export const USER_VACATION_DISABLED = 'USER_VACATION_DISABLED';
export const USER_DATA_EXPORTED = 'USER_DATA_EXPORTED';
export const USER_DELETED_SOFT = 'USER_DELETED_SOFT';
export const USER_ANONYMIZED = 'USER_ANONYMIZED';
export const USER_TEAM_INVITED = 'USER_TEAM_INVITED';
export const USER_TEAM_REMOVED = 'USER_TEAM_REMOVED';
export const USER_OWNERSHIP_TRANSFERRED = 'USER_OWNERSHIP_TRANSFERRED';

// Revenue Events
export const REVENUE_FEE_SCHEDULE_CREATED = 'REVENUE_FEE_SCHEDULE_CREATED';
export const REVENUE_FEE_SCHEDULE_ACTIVATED = 'REVENUE_FEE_SCHEDULE_ACTIVATED';
export const REVENUE_PROMO_ISSUED = 'REVENUE_PROMO_ISSUED';
export const REVENUE_CREDIT_ISSUED = 'REVENUE_CREDIT_ISSUED';
export const REVENUE_FEE_RECALCULATED = 'REVENUE_FEE_RECALCULATED';
export const REVENUE_PAYOUT_ADJUSTED = 'REVENUE_PAYOUT_ADJUSTED';
export const REVENUE_REFUND_POLICY_UPDATED = 'REVENUE_REFUND_POLICY_UPDATED';
export const REVENUE_DISPUTE_DECISION = 'REVENUE_DISPUTE_DECISION';

// Order Events
export const ORDER_STATE_CHANGED = 'ORDER_STATE_CHANGED';
export const ORDER_REFUNDED = 'ORDER_REFUNDED';
export const ORDER_EDITED = 'ORDER_EDITED';
export const ORDER_CANCELLED = 'ORDER_CANCELLED';
export const ORDER_CREATED = 'ORDER_CREATED';

// Inventory Events
export const INVENTORY_ADJUSTMENT = 'INVENTORY_ADJUSTMENT';
export const INVENTORY_WASTE_LOGGED = 'INVENTORY_WASTE_LOGGED';
export const INVENTORY_RECIPE_RUN = 'INVENTORY_RECIPE_RUN';
export const INVENTORY_REORDER = 'INVENTORY_REORDER';

// Messaging & CRM Events
export const MESSAGE_BROADCAST_SENT = 'MESSAGE_BROADCAST_SENT';
export const MESSAGE_THREAD_JOINED_ADMIN = 'MESSAGE_THREAD_JOINED_ADMIN';
export const MESSAGE_NOTE_CREATED = 'MESSAGE_NOTE_CREATED';
export const MESSAGE_TASK_CREATED = 'MESSAGE_TASK_CREATED';
export const MESSAGE_TASK_CLOSED = 'MESSAGE_TASK_CLOSED';

// Event (Coordinator) Events
export const EVENT_CREATED = 'EVENT_CREATED';
export const EVENT_UPDATED = 'EVENT_UPDATED';
export const EVENT_STALL_TIER_EDITED = 'EVENT_STALL_TIER_EDITED';
export const EVENT_SETTLEMENT_CLOSED = 'EVENT_SETTLEMENT_CLOSED';
export const EVENT_DELETED = 'EVENT_DELETED';

// Config Events
export const CONFIG_WEBHOOK_SECRET_ROTATED = 'CONFIG_WEBHOOK_SECRET_ROTATED';
export const CONFIG_API_KEY_ROTATED = 'CONFIG_API_KEY_ROTATED';
export const CONFIG_POLICY_TOGGLED = 'CONFIG_POLICY_TOGGLED';
export const CONFIG_TAX_SYNC = 'CONFIG_TAX_SYNC';
export const CONFIG_STRIPE_SYNC = 'CONFIG_STRIPE_SYNC';
export const CONFIG_WEBHOOK_ADDED = 'CONFIG_WEBHOOK_ADDED';
export const CONFIG_ENVIRONMENT_CHANGED = 'CONFIG_ENVIRONMENT_CHANGED';

// Privacy Operations Events
export const PRIVACY_SAR_REQUESTED = 'PRIVACY_SAR_REQUESTED';
export const PRIVACY_SAR_FULFILLED = 'PRIVACY_SAR_FULFILLED';
export const PRIVACY_SAR_DENIED = 'PRIVACY_SAR_DENIED';
export const PRIVACY_DATA_EXPORTED = 'PRIVACY_DATA_EXPORTED';
export const PRIVACY_DELETE_REQUESTED = 'PRIVACY_DELETE_REQUESTED';
export const PRIVACY_ANONYMIZE_REQUESTED = 'PRIVACY_ANONYMIZE_REQUESTED';

// Account Events
export const ACCOUNT_CREATED = 'ACCOUNT_CREATED';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const ACCOUNT_SETTINGS_UPDATED = 'ACCOUNT_SETTINGS_UPDATED';

// Support Events
export const SUPPORT_TICKET_CREATED = 'SUPPORT_TICKET_CREATED';
export const SUPPORT_TICKET_ASSIGNED = 'SUPPORT_TICKET_ASSIGNED';
export const SUPPORT_TICKET_STATUS_CHANGED = 'SUPPORT_TICKET_STATUS_CHANGED';
export const SUPPORT_TICKET_ESCALATED = 'SUPPORT_TICKET_ESCALATED';
export const SUPPORT_TICKET_RESOLVED = 'SUPPORT_TICKET_RESOLVED';
export const SUPPORT_TICKET_CLOSED = 'SUPPORT_TICKET_CLOSED';
export const SUPPORT_TICKET_DELETED = 'SUPPORT_TICKET_DELETED';
export const SUPPORT_TICKET_MESSAGE_ADDED = 'SUPPORT_TICKET_MESSAGE_ADDED';
export const SUPPORT_TICKET_ATTACHMENT_ADDED = 'SUPPORT_TICKET_ATTACHMENT_ADDED';
export const SUPPORT_TICKET_REOPENED = 'SUPPORT_TICKET_REOPENED';

// Ops Events
export const OPS_CACHE_FLUSHED = 'OPS_CACHE_FLUSHED';
export const OPS_QUEUE_ACTION = 'OPS_QUEUE_ACTION';
export const OPS_DB_MAINTENANCE = 'OPS_DB_MAINTENANCE';
export const OPS_MIGRATION_RUN = 'OPS_MIGRATION_RUN';
export const OPS_BACKUP_INITIATED = 'OPS_BACKUP_INITIATED';
export const OPS_WEBHOOK_REPLAYED = 'OPS_WEBHOOK_REPLAYED';
export const OPS_SECRET_ROTATED = 'OPS_SECRET_ROTATED';
export const OPS_TOOL_EXECUTED = 'OPS_TOOL_EXECUTED';
export const OPS_SEARCH_REINDEXED = 'OPS_SEARCH_REINDEXED';
export const OPS_READONLY_TOGGLED = 'OPS_READONLY_TOGGLED';
export const INCIDENT_CREATED = 'INCIDENT_CREATED';
export const INCIDENT_STATUS_CHANGED = 'INCIDENT_STATUS_CHANGED';
export const INCIDENT_TIMELINE_ADDED = 'INCIDENT_TIMELINE_ADDED';
export const CONFIG_MAINTENANCE_MODE_TOGGLED = 'CONFIG_MAINTENANCE_MODE_TOGGLED';
export const CONFIG_FEATURE_FLAG_TOGGLED = 'CONFIG_FEATURE_FLAG_TOGGLED';

// All event codes as a type
export type AuditEventCode = 
  // Auth
  | typeof AUTH_LOGIN_SUCCESS
  | typeof AUTH_LOGIN_FAIL
  | typeof AUTH_PASSWORD_RESET
  | typeof AUTH_PASSWORD_CHANGED
  | typeof AUTH_MFA_ENROLLED
  | typeof AUTH_MFA_REMOVED
  | typeof AUTH_IMPERSONATION_STARTED
  | typeof AUTH_IMPERSONATION_ENDED
  | typeof AUTH_SESSION_TERMINATED
  | typeof AUTH_LOGOUT
  // User
  | typeof USER_CREATED
  | typeof USER_UPDATED
  | typeof USER_SUSPENDED
  | typeof USER_REINSTATED
  | typeof USER_ROLE_GRANTED
  | typeof USER_ROLE_REVOKED
  | typeof USER_MERGED
  | typeof USER_VACATION_ENABLED
  | typeof USER_VACATION_DISABLED
  | typeof USER_DATA_EXPORTED
  | typeof USER_DELETED_SOFT
  | typeof USER_ANONYMIZED
  | typeof USER_TEAM_INVITED
  | typeof USER_TEAM_REMOVED
  | typeof USER_OWNERSHIP_TRANSFERRED
  // Revenue
  | typeof REVENUE_FEE_SCHEDULE_CREATED
  | typeof REVENUE_FEE_SCHEDULE_ACTIVATED
  | typeof REVENUE_PROMO_ISSUED
  | typeof REVENUE_CREDIT_ISSUED
  | typeof REVENUE_FEE_RECALCULATED
  | typeof REVENUE_PAYOUT_ADJUSTED
  | typeof REVENUE_REFUND_POLICY_UPDATED
  | typeof REVENUE_DISPUTE_DECISION
  // Order
  | typeof ORDER_STATE_CHANGED
  | typeof ORDER_REFUNDED
  | typeof ORDER_EDITED
  | typeof ORDER_CANCELLED
  | typeof ORDER_CREATED
  // Inventory
  | typeof INVENTORY_ADJUSTMENT
  | typeof INVENTORY_WASTE_LOGGED
  | typeof INVENTORY_RECIPE_RUN
  | typeof INVENTORY_REORDER
  // Messaging
  | typeof MESSAGE_BROADCAST_SENT
  | typeof MESSAGE_THREAD_JOINED_ADMIN
  | typeof MESSAGE_NOTE_CREATED
  | typeof MESSAGE_TASK_CREATED
  | typeof MESSAGE_TASK_CLOSED
  // Event
  | typeof EVENT_CREATED
  | typeof EVENT_UPDATED
  | typeof EVENT_STALL_TIER_EDITED
  | typeof EVENT_SETTLEMENT_CLOSED
  | typeof EVENT_DELETED
  // Config
  | typeof CONFIG_WEBHOOK_SECRET_ROTATED
  | typeof CONFIG_API_KEY_ROTATED
  | typeof CONFIG_POLICY_TOGGLED
  | typeof CONFIG_TAX_SYNC
  | typeof CONFIG_STRIPE_SYNC
  | typeof CONFIG_WEBHOOK_ADDED
  | typeof CONFIG_ENVIRONMENT_CHANGED
  // Privacy
  | typeof PRIVACY_SAR_REQUESTED
  | typeof PRIVACY_SAR_FULFILLED
  | typeof PRIVACY_SAR_DENIED
  | typeof PRIVACY_DATA_EXPORTED
  | typeof PRIVACY_DELETE_REQUESTED
  | typeof PRIVACY_ANONYMIZE_REQUESTED
  // Account
  | typeof ACCOUNT_CREATED
  | typeof ACCOUNT_DELETED
  | typeof ACCOUNT_SETTINGS_UPDATED
  // Support
  | typeof SUPPORT_TICKET_CREATED
  | typeof SUPPORT_TICKET_ASSIGNED
  | typeof SUPPORT_TICKET_STATUS_CHANGED
  | typeof SUPPORT_TICKET_ESCALATED
  | typeof SUPPORT_TICKET_RESOLVED
  | typeof SUPPORT_TICKET_CLOSED
  | typeof SUPPORT_TICKET_DELETED
  | typeof SUPPORT_TICKET_MESSAGE_ADDED
  | typeof SUPPORT_TICKET_ATTACHMENT_ADDED
  | typeof SUPPORT_TICKET_REOPENED
  // Ops
  | typeof OPS_CACHE_FLUSHED
  | typeof OPS_QUEUE_ACTION
  | typeof OPS_DB_MAINTENANCE
  | typeof OPS_MIGRATION_RUN
  | typeof OPS_BACKUP_INITIATED
  | typeof OPS_WEBHOOK_REPLAYED
  | typeof OPS_SECRET_ROTATED
  | typeof OPS_TOOL_EXECUTED
  | typeof OPS_SEARCH_REINDEXED
  | typeof OPS_READONLY_TOGGLED
  | typeof INCIDENT_CREATED
  | typeof INCIDENT_STATUS_CHANGED
  | typeof INCIDENT_TIMELINE_ADDED
  | typeof CONFIG_MAINTENANCE_MODE_TOGGLED
  | typeof CONFIG_FEATURE_FLAG_TOGGLED;

// Critical events that should trigger alerts
export const CRITICAL_EVENTS = new Set([
  AUTH_IMPERSONATION_STARTED,
  AUTH_IMPERSONATION_ENDED,
  USER_ROLE_GRANTED,
  USER_DELETED_SOFT,
  USER_ANONYMIZED,
  REVENUE_FEE_SCHEDULE_ACTIVATED,
  REVENUE_PAYOUT_ADJUSTED,
  CONFIG_WEBHOOK_SECRET_ROTATED,
  CONFIG_API_KEY_ROTATED,
  PRIVACY_SAR_REQUESTED,
  PRIVACY_DELETE_REQUESTED,
  PRIVACY_ANONYMIZE_REQUESTED,
  ACCOUNT_DELETED,
  OPS_MIGRATION_RUN,
  OPS_SECRET_ROTATED,
  OPS_READONLY_TOGGLED,
  CONFIG_MAINTENANCE_MODE_TOGGLED,
  INCIDENT_CREATED,
]);

// Event category helpers
export function isAuthEvent(action: string): boolean {
  return action.startsWith('AUTH_');
}

export function isPrivacyEvent(action: string): boolean {
  return action.startsWith('PRIVACY_');
}

export function isRevenueEvent(action: string): boolean {
  return action.startsWith('REVENUE_');
}

export function isCriticalEvent(action: string): boolean {
  return CRITICAL_EVENTS.has(action);
}

export function isOpsEvent(action: string): boolean {
  return action.startsWith('OPS_') || action.startsWith('INCIDENT_');
}

