version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: craved-artisan-db
    environment:
      POSTGRES_DB: craved_artisan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - craved-artisan-network

  # Redis (for caching)
  redis:
    image: redis:7-alpine
    container_name: craved-artisan-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - craved-artisan-network

  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: craved-artisan-server
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/craved_artisan
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - craved-artisan-network
    command: npm run dev

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: craved-artisan-client
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - server
    networks:
      - craved-artisan-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  craved-artisan-network:
    driver: bridge 